import { describe, it } from 'vitest';

describe('coverage workflow (flowdeck)', () => {
  // flowdeck doesn't have coverage report extraction tools
  // Coverage is generated by xcodebuild test but flowdeck doesn't expose
  // get-coverage-report or get-file-coverage equivalents
  it.skip('no flowdeck equivalent for coverage report extraction', () => {});
});
